### ISSUE TITLE
Is there a pre-computed knapsack file available?

### ISSUE THREAD

**Issue by lostculture** [instadeepai/InstaNovo#16]
The minconda command line instructions have a --knapsack_path variable. Is this required? If so will a pre-computed knapsack file be made available? Or command line instructions on how to generate it?
I found the model checkpoints so those are covered.
The only other suggestions is making an example input file available, from one of the analysis in the paper and in .ipc format, so that the software can be run straight away and produce good quality output.
It looks very interesting and I'm looking forward to trying out some other data with the system.

**Comment by amabinsta** [comment]
Hi @lostculture,

Thanks for your interest and for the suggestions.  I'll pass them on to the rest of the team for discussion and give you an update. 

To answer your question, `--knapsack_path` would be the path to a saved knapsack. This would be the path you saved a knapsack to by calling `knapsack.save(knapsack_path)`. The following lines from the example `Colab` notebook show how a knapsack can be constructed, saved and loaded.
```
def _setup_knapsack(model: InstaNovo) -> Knapsack:
    MASS_SCALE = 10000
    residue_masses = model.peptide_mass_calculator.masses
    residue_masses["$"] = 0
    residue_indices = model.decoder._aa2idx
    return Knapsack.construct_knapsack(
        residue_masses=residue_masses,
        residue_indices=residue_indices,
        max_mass=4000.00,
        mass_scale=MASS_SCALE,
    )

knapsack_path = "./checkpoints/knapsack/"

if not os.path.exists(knapsack_path):
    print("Knapsack path missing or not specified, generating...")
    knapsack = _setup_knapsack(model)
    decoder = KnapsackBeamSearchDecoder(model, knapsack)
    print(f"Saving knapsack to {knapsack_path}")
    knapsack.save(knapsack_path)
else:
    print("Knapsack path found. Loading...")
    decoder = KnapsackBeamSearchDecoder.from_file(model=model, path=knapsack_path)
```

In general, the `Knapsack` class in `instanovo.inference.knapsack` has the instance method `save` for saving a knapsack to a directory (called like `knapsack.save(...)`) and the class methods `construct_knapsack` for constructing a knapsack for a given set of residues and `from_file` for loading a saved knapsack from a directory (called like `Knapsack.construct_knapsack(...)` and `Knapsack.from_file(...)`). But, as I said, we'll discuss expanding on this example to make it clearer and get back to you.

**Comment by lostculture** [comment]
Thanks @amabinsta for getting back to me so quickly. 
I'm not much of a programmer and am more interested in using the software. I did see the code in the Colab notebook but don't know how to use it. I went the miniconda route. As the --knapsack_path is optional then the software looks to be ready to use once I have an input file. I saw the conversion instructions so it looks like I'm all set.

**Comment by BioGeek** [comment]
> I did see the code in the Colab notebook but don't know how to use it.

There is an <a target="_blank" href="https://colab.research.google.com/github/instadeepai/InstaNovo/blob/main/notebooks/getting_started_with_instanovo.ipynb">
<img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/> </a>   button at the top of the notebook. If you click on that button it should open the `getting_started_with_instanovo.ipynb` notebook in Google Colab at [https://colab.research.google.com/github/instadeepai/InstaNovo/blob/main/notebooks/getting_started_with_instanovo.ipynb](https://colab.research.google.com/github/instadeepai/InstaNovo/blob/main/notebooks/getting_started_with_instanovo.ipynb).

Go to `Runtime` >  `Change Runtime type` and confirm that a T4 GPU is selected.
Then go to `Runtime` > `Run all` and click `Run anyway` on the warning.
This will start the installation of `instanovo`, load the  nine-species dataset and run inference on them.

You can also [upload your own data](https://stackoverflow.com/a/59071557/50065) as `*.ipc` file and  run inference on them.

**Comment by BioGeek** [comment]
Hello @lostculture ,

Have all your questions in this issue been answered and can this issue be closed?

**Comment by lostculture** [comment]
Thank you for the instructions on using the Colab notebook. I'm more from a proteomics background and behind the times on the notebooks. I was really looking to run the code locally. I was also confused on whether I needed a predefined knapsack_path and file but now see that it will generated even if you don't have one `INFO:root:Knapsack path missing or not specified, generating...`.

Yes, case closed.
