### ISSUE TITLE
TypeError in convert_to_ipc when comparing charge values

### ISSUE THREAD

**Issue by cliang-huanglab** [instadeepai/InstaNovo#39]
**Issue Description:**
When attempting to convert MGF files to IPC format using the convert_to_ipc utility, a TypeError is raised during the execution. This error occurs when the script tries to compare the charge value from metadata, which is a string, with the max_charge parameter, which is an integer.

**Steps to Reproduce:**

1. Navigate to the InstaNovo utils directory.
2. Run the command:
`python -m convert_to_ipc sample_preprocessed_spectra.mgf sample_preprocessed_spectra.ipc --source_type mgf --max_charge 7`
3. Observe the TypeError as described.

**Expected Behavior:**
The script should correctly compare the charge values from the MGF metadata with the max_charge integer without type mismatch errors, possibly by ensuring all comparisons are done between integers.

**Actual Behavior:**
The script raises a TypeError due to a mismatch in data types when comparing charge from the metadata (string) with max_charge (integer):

> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/mnt/data_nas/lcy/project_Denovo/5.tools/InstaNovo-main/instanovo/utils/convert_to_ipc.py", line 304, in <module>
>     main()
>   File "/mnt/data_nas/lcy/project_Denovo/5.tools/InstaNovo-main/instanovo/utils/convert_to_ipc.py", line 279, in main
>     convert_mgf_ipc(
>   File "/mnt/data_nas/lcy/project_Denovo/5.tools/InstaNovo-main/instanovo/utils/convert_to_ipc.py", line 97, in convert_mgf_ipc
>     if "charge" not in meta or meta["charge"] > max_charge:
> TypeError: '>' not supported between instances of 'int' and 'str'

**Comment by rcatzel** [comment]
Hi @cliang-huanglab,

Apologies for the delayed response.

We have recently released InstaNovo 1.0.0 which features new scripts to handle data conversion. The [convert_to_sdf.py](https://github.com/instadeepai/InstaNovo/blob/main/instanovo/scripts/convert_to_sdf.py) script is what you would use now, and the issue you described should be fixed.
